// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechBeyondThoughts.Services.EBookAPI.Data;

#nullable disable

namespace TechBeyondThoughts.Services.EBookAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231219105147_newchanges1")]
    partial class newchanges1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechBeyondThoughts.Services.EBookAPI.Models.BookData", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Downloads")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pages")
                        .HasColumnType("int");

                    b.Property<DateTime>("Published")
                        .HasColumnType("datetime2");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.ToTable("Bookstacks");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "Author 1",
                            Category = "Fiction",
                            Description = "Description 1",
                            Downloads = 100,
                            FileName = "book1.pdf",
                            FilePath = "/storage/book1.pdf",
                            Format = "PDF",
                            Pages = 200,
                            Published = new DateTime(2023, 12, 19, 16, 21, 46, 836, DateTimeKind.Local).AddTicks(4886),
                            Rating = 4.5,
                            Title = "Book 1"
                        });
                });

            modelBuilder.Entity("TechBeyondThoughts.Services.EBookAPI.Models.BookPreview", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("PagesToPreview")
                        .HasColumnType("int");

                    b.HasKey("BookId");

                    b.ToTable("BookPreviews");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            PagesToPreview = 5
                        });
                });

            modelBuilder.Entity("TechBeyondThoughts.Services.EBookAPI.Models.DownloadHistory", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DownloadDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BookId");

                    b.ToTable("DownloadHistory");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            DownloadDateTime = new DateTime(2023, 12, 19, 16, 21, 46, 836, DateTimeKind.Local).AddTicks(5158),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("TechBeyondThoughts.Services.EBookAPI.Models.Rating", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("BookId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            UserId = 1,
                            Value = 4.0
                        });
                });

            modelBuilder.Entity("TechBeyondThoughts.Services.EBookAPI.Models.BookPreview", b =>
                {
                    b.HasOne("TechBeyondThoughts.Services.EBookAPI.Models.BookData", "Book")
                        .WithOne("BookPreview")
                        .HasForeignKey("TechBeyondThoughts.Services.EBookAPI.Models.BookPreview", "BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("TechBeyondThoughts.Services.EBookAPI.Models.DownloadHistory", b =>
                {
                    b.HasOne("TechBeyondThoughts.Services.EBookAPI.Models.BookData", "Book")
                        .WithMany("DownloadHistory")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("TechBeyondThoughts.Services.EBookAPI.Models.Rating", b =>
                {
                    b.HasOne("TechBeyondThoughts.Services.EBookAPI.Models.BookData", "Book")
                        .WithMany("Ratings")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("TechBeyondThoughts.Services.EBookAPI.Models.BookData", b =>
                {
                    b.Navigation("BookPreview")
                        .IsRequired();

                    b.Navigation("DownloadHistory");

                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
